### ISSUE TITLE
error when using train_dist.py

### ISSUE THREAD

**Issue by Altheim** [Tengfei-Wang/Implicit-Internal-Video-Inpainting#7]
when I use tensorflow 2.4：
AttributeError: 'MirroredStrategy' object has no attribute 'experimental_run_v2'
I need to downgrade to tensorflow 2.0

when I use  tensorflow 2.0：
ImportError:cannot import name 'keras_tensor' from 'tensorflow.python.keras.engine' (/home/ivdai/anaconda3/envs/IIVI/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/__init__.py)
I need to upgrade to tensorflow 2.4 

funny

**Comment by Altheim** [comment]
it works with tensoflow-gpu=2.0.0 and tensorflow-addons=0.6.0
